### ISSUE TITLE
problems with use on mobile

### ISSUE THREAD

**Issue by Dan-Vizor** [soruly/trace.moe#20] opened 2018-07-27 19:55 UTC
the site seems to show "no results" for images on android which when uploaded on desktop work.

example:
![desktop](https://user-images.githubusercontent.com/28623546/43343744-4dc9af56-91df-11e8-845a-b8d8d8a4834c.PNG)
![mobile](https://user-images.githubusercontent.com/28623546/43343745-4e1e7252-91df-11e8-9f40-463c0e5e91ea.jpg)

**Comment by soruly** [comment] 2018-07-28 05:53
It works fine on my device (Android 6.0.1 Chrome 67.0)
I think it may be temporary issue on server-side database, would you try again?

**Comment by Dan-Vizor** [comment] 2018-07-30 00:36
No still doesn't work (Android 8.0.0 Brave 1.0.52) but looks like it might be a Brave compatibility problem as it works on Chrome

**Comment by soruly** [comment] 2018-07-30 04:32
Oh I haven't heard about this browser, I'll take a look

**Comment by soruly** [comment] 2018-07-30 07:55
Hi @Dan-Vizor it appears you've enabled fingerprinting protection in Brave's setting. Try turning it off and search again. I've no idea how Brave classify an HTTP request as fingerprinting though :\

**Comment by soruly** [comment] 2018-07-30 07:58
I've also found that the video preview is not showing on Brave's browser. This would be another issue I will to look into.

**Comment by Genteure** [comment] 2018-07-30 08:15
fingerprinting protection usually blocks/interference canvas APIs, some complete blocks toDataURL/toBlob, some overwrite APIs to return a modified data.

https://www.browserleaks.com/canvas

**Comment by soruly** [comment] 2018-07-30 08:17
![image](https://user-images.githubusercontent.com/1979746/43385682-f4149ad4-9413-11e8-8fea-8f004690d745.png)
Yes, it appears that when fingerprinting protection is on, the search request becomes sending empty data to the server, resulting a "no result" from database search.

**Comment by soruly** [comment] 2018-07-30 08:22
![image](https://user-images.githubusercontent.com/1979746/43385935-b034bd66-9414-11e8-840d-cafff479a728.png)
toDataURL returned an empty string.
I think this issue should be handled by alerting the users that something is wrong before send the search request to server, rather than showing "no result".

**Comment by Dan-Vizor** [comment] 2018-07-30 23:11
No tried turning fingerprint protection off but still getting "no results"

**Comment by soruly** [comment] 2018-07-31 04:31
Try turning all the options all off?

**Comment by soruly** [comment] 2018-07-31 04:31
And maybe try to clear cache

**Comment by Dan-Vizor** [comment] 2018-07-31 11:12
Everything off and still nothing

**Comment by soruly** [comment] 2018-07-31 12:31
I've tried Brave on Android 8.1.0 and Android 5.1.1 and still cannot reproduce this issue with default settings. 
Note that on Android, you can use the app from play store
https://play.google.com/store/apps/details?id=com.maddog05.whatanime
https://play.google.com/store/apps/details?id=pw.janyo.whatanime

or if you prefer not to install app, you can just use Telegram and forward/share images to the bot http://t.me/whatanimebot

**Comment by soruly** [comment] 2018-10-27 06:07
Tried again with latest version of Brave browser with default options (fingerprinting off)
Cannot reproduce on https://trace.moe 
Closing this issue

**Closed by soruly** 2018-10-27 06:07 UTC
